{
 "title": "CredPol",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Sentimiento",
   "type": "gauge",
   "description": "Sentimiento general del usuario",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "queryText": "select \nCAST(strftime('%s',start_time,'-1 minute') as INTEGER) as time, \nsentiment_score\nfrom prompt_responses\nwhere start_time is not null\norder by start_time",
     "rawQueryText": "select \nCAST(strftime('%s',start_time,'-1 minute') as INTEGER) as time, \nsentiment_score\nfrom prompt_responses\nwhere start_time is not null\norder by start_time",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Preguntas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \ncount(1) Preguntas\nfrom prompt_responses",
     "rawQueryText": "select \ncount(1) Preguntas\nfrom prompt_responses",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 15, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select\ncount(1) as cnt,\nrequest_type\nfrom prompt_responses\ngroup by request_type;",
     "rawQueryText": "select\ncount(1) as cnt,\nrequest_type\nfrom prompt_responses\ngroup by request_type;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Apertura Sentimiento",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n\tsentiment_category,\n\tsum(cnt) cnt\nFROM (\nSELECT \n    1 cnt,\n    CASE\n        WHEN sentiment_score BETWEEN -1 AND -0.65 THEN 'Muy Negativo'\n        WHEN sentiment_score BETWEEN -0.65 AND -0.05 THEN 'Negativo'\n        WHEN sentiment_score BETWEEN -0.05 AND 0.05 THEN 'Neutro'\n        WHEN sentiment_score BETWEEN 0.05 AND 0.65 THEN 'Positivo'\n        WHEN sentiment_score BETWEEN 0.65 AND 1 THEN 'Muy Positivo'\n    END AS sentiment_category\nFROM \n    prompt_responses\n) C\nGROUP BY \n\tC.sentiment_category;",
     "rawQueryText": "SELECT \n\tsentiment_category,\n\tsum(cnt) cnt\nFROM (\nSELECT \n    1 cnt,\n    CASE\n        WHEN sentiment_score BETWEEN -1 AND -0.65 THEN 'Muy Negativo'\n        WHEN sentiment_score BETWEEN -0.65 AND -0.05 THEN 'Negativo'\n        WHEN sentiment_score BETWEEN -0.05 AND 0.05 THEN 'Neutro'\n        WHEN sentiment_score BETWEEN 0.05 AND 0.65 THEN 'Positivo'\n        WHEN sentiment_score BETWEEN 0.65 AND 1 THEN 'Muy Positivo'\n    END AS sentiment_category\nFROM \n    prompt_responses\n) C\nGROUP BY \n\tC.sentiment_category;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta",
   "type": "gauge",
   "description": "Tiempo de Respuesta del LLM",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select \nAVG((strftime('%s', end_time) - strftime('%s', start_time))) AS [Tiempo respuesta]\nfrom prompt_responses",
     "rawQueryText": "select \nAVG((strftime('%s', end_time) - strftime('%s', start_time))) AS [Tiempo respuesta]\nfrom prompt_responses",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Apertura por canal",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "queryText": "select\ncount(1) as cnt,\nchanel\nfrom msg_chanel\ngroup by chanel;",
     "rawQueryText": "select\ncount(1) as cnt,\nchanel\nfrom msg_chanel\ngroup by chanel;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Estado de los servicios",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT\n\tCAST(strftime('%s',fechaRegistro,'-1 minute') as INTEGER) as time,\n\tIndicador as Servicio,\n\tiValor as Last\nFROM indicadores\nWHERE \n\tIndicador IN('Messaging service status','Llm service status')\n\t--AND D.time >= $__from / 1000 and D.time < $__to / 1000\nORDER BY IDX ASC;\n--LIMIT 1000;",
     "rawQueryText": "SELECT\n\tCAST(strftime('%s',fechaRegistro,'-1 minute') as INTEGER) as time,\n\tIndicador as Servicio,\n\tiValor as Last\nFROM indicadores\nWHERE \n\tIndicador IN('Messaging service status','Llm service status')\n\t--AND D.time >= $__from / 1000 and D.time < $__to / 1000\nORDER BY IDX ASC;\n--LIMIT 1000;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SLA",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n\tD.Indicador,\n\tSUM(D.Ok) Ok,\n\tSUM(D.Error) Errores\nFROM (\n\tSELECT \n\t\tCAST(strftime('%s',fechaRegistro,'-1 minute') as INTEGER) as time,\n\t\tIndicador,\n\t\tCASE WHEN iValor > 0 THEN 1 ELSE 0 END as Ok,\n\t\tCASE WHEN iValor < 0 THEN 1 ELSE 0 END as Error,\n\t\tABS(iValor) Total\n\tFROM indicadores\n) D\nWHERE D.time >= $__from / 1000 and D.time < $__to / 1000\nGROUP BY \n\tD.Indicador",
     "rawQueryText": "SELECT\n\tD.Indicador,\n\tSUM(D.Ok) Ok,\n\tSUM(D.Error) Errores\nFROM (\n\tSELECT \n\t\tCAST(strftime('%s',fechaRegistro,'-1 minute') as INTEGER) as time,\n\t\tIndicador,\n\t\tCASE WHEN iValor > 0 THEN 1 ELSE 0 END as Ok,\n\t\tCASE WHEN iValor < 0 THEN 1 ELSE 0 END as Error,\n\t\tABS(iValor) Total\n\tFROM indicadores\n) D\nWHERE D.time >= $__from / 1000 and D.time < $__to / 1000\nGROUP BY \n\tD.Indicador",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Uso de recursos", "type": "timeseries", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 } }
 ]
}